### PR TITLE
fix(deps): switch to psycopg2-binary

### PR DESCRIPTION
**Pull request by ojongerius**
Makes building on macOS a little easier

### CODE REVIEW

**Review by ranrib — APPROVED** [review]

**Review by ophiryael — APPROVED** [review]
Thanks for the help @ojongerius !

**Comment by ojongerius** [comment]
@ophiryael CI is failing due to `AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.`. Assuming that's due to this PR being from my fork.

**Comment by ojongerius** [comment]
Same code passed in test PR by @ranrib at https://github.com/epsagon/epsagon-python/pull/372

**Comment by ophiryael** [comment]
@ojongerius You are correct, our current setup doesn't play well with PRs from forks. We are aware of the issue and working on resolving it.

**Comment by ranrib** [comment]
I've added you as an external collaborator @ojongerius :) so moving forward such PRs will work

**Comment by ranrib** [comment]
For future note - I've tested this PR here https://github.com/epsagon/epsagon-python/pull/372, but merging this one

**Pull request merged**
