### PR TITLE
feat(aws_lambda): do not trace warmup events from serverless-plugin-warmup plugin

### PR DESCRIPTION
**Pull request by ojongerius**
👋 We started using Epsagon and are looking for a way to use `serverless-plugin-epsagon` in combination with `serverless-plugin-warmup`.

This however would work perfectly for us, it enables us to let the plugin do the heavy lifting which would work for most of our projects, and still use the warmup plugin.

Other ideas, of which the fist has my preference:
1. Add a key like `ignoredPayloads` to https://github.com/epsagon/serverless-plugin-epsagon which could take a dict like `{"source": "serverless-plugin-warmup"}` or list of dicts. If enabled, use that/those patterns in https://github.com/epsagon/epsagon-python . One upside would be that it removes hardcoding a payload currently generated by the warmup plugin and could support other use cases.
2. Allow people to bring their own wrappers for your wrapper. Not sure if I'm a fan of this but it's something that I looked for as a way to solve my problem.

I've raised https://github.com/epsagon/serverless-plugin-epsagon/issues/106 suggesting option one to see if there is an appetite for it.

### CODE REVIEW

**Comment by ojongerius** [comment]
Other ideas:
* Add a key like `ignoredPayloads` to https://github.com/epsagon/serverless-plugin-epsagon which could take a dict like `{"source": "serverless-plugin-warmup"}` or list of dicts. If enabled, use that/those patterns in https://github.com/epsagon/epsagon-python . One upside would be that it removes hardcoding a payload currently generated by the warmup plugin and could support other use cases.
* Allow people to bring their own wrappers for your wrapper. Not sure if I'm a fan of this but it's something that I looked for as a way to solve my problem.

**Comment by ojongerius** [comment]
I've added 72124928a945fbb18b3c93e9dd69d79ebfb9c7a9 which allows configuring payloads to ignore using an environment variable. This sets us up to configure this using the sls plugin 🥳

**Comment by ranrib** [comment]
Really great contribution @ojongerius! as you got the permissions now, do you mind re-creating this branch from this repo so travis will work?

Thanks

**Comment by ojongerius** [comment]
@ranrib cheers! Are you sure you gave me write rights?

Remote setup:

```
▶ git remote -v
origin  git@github.com:epsagon/epsagon-python.git (fetch)
origin  git@github.com:epsagon/epsagon-python.git (push)
otto    git@github.com:ojongerius/epsagon-python.git (fetch)
otto    git@github.com:ojongerius/epsagon-python.git (push)
(venv) 
~/repos/epsagon-python  dont_trace_warmup ✔                                                                                                                                                                     5d0h
```

Trying to push branch to origin:

```  
▶ git push origin dont_trace_warmup
ERROR: Permission to epsagon/epsagon-python.git denied to ojongerius.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ranrib** [comment]
I see it's still pending invite @ojongerius 
image

Did you get the invite to your email?

**Comment by ojongerius** [comment]
Completely missed the invite. Accepted and just pushed branch and raised #373 👍

**Pull request closed without merging**
