### PR TITLE
feat(fastapi): added ignored endpoints

### PR DESCRIPTION
**Pull request by sagivr2020**

### CODE REVIEW

**Review by adavidai — COMMENTED** [review]
Looks good 👍 
How about adding a test for the ignored endpoint functionality to the existing fastapi tests?

**Comment by sagivr2020** [comment]
According to "run_tests.sh" file - pytest ignored FastAPI tests.
Therefore I added fastapi_example.py for testing.

**Review by adavidai — APPROVED** [review]
Adding a ticket for enabling the tests back, once we do let's add this test as well

**Pull request merged**
